<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
PEP, see http://www.python.org/dev/peps/pep-0001 for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->
<table class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">PEP:</th><td class="field-body">343</td>
</tr>
<tr class="field"><th class="field-name">Title:</th><td class="field-body">The &quot;with&quot; Statement</td>
</tr>
<tr class="field"><th class="field-name">Version:</th><td class="field-body">$Revision$</td>
</tr>
<tr class="field"><th class="field-name">Last-Modified:</th><td class="field-body"><a class="reference external" href="https://hg.python.org/peps/file/tip/pep-0343.txt">$Date$</a></td>
</tr>
<tr class="field"><th class="field-name">Author:</th><td class="field-body">Guido van Rossum, Nick Coghlan</td>
</tr>
<tr class="field"><th class="field-name">Status:</th><td class="field-body">Final</td>
</tr>
<tr class="field"><th class="field-name">Type:</th><td class="field-body">Standards Track</td>
</tr>
<tr class="field"><th class="field-name">Content-Type:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0012">text/x-rst</a></td>
</tr>
<tr class="field"><th class="field-name">Created:</th><td class="field-body">13-May-2005</td>
</tr>
<tr class="field"><th class="field-name">Python-Version:</th><td class="field-body">2.5</td>
</tr>
<tr class="field"><th class="field-name">Post-History:</th><td class="field-body">2-Jun-2005, 16-Oct-2005, 29-Oct-2005, 23-Apr-2006, 1-May-2006, 30-Jul-2006</td>
</tr>
</tbody>
</table>
<hr />
<div class="contents topic" id="contents">
<p class="topic-title first">Contents</p>
<ul class="simple">
<li><a class="reference internal" href="#abstract" id="id33">Abstract</a></li>
<li><a class="reference internal" href="#author-s-note" id="id34">Author's Note</a></li>
<li><a class="reference internal" href="#introduction" id="id35">Introduction</a></li>
<li><a class="reference internal" href="#motivation-and-summary" id="id36">Motivation and Summary</a></li>
<li><a class="reference internal" href="#use-cases" id="id37">Use Cases</a></li>
<li><a class="reference internal" href="#specification-the-with-statement" id="id38">Specification: The 'with' Statement</a></li>
<li><a class="reference internal" href="#transition-plan" id="id39">Transition Plan</a></li>
<li><a class="reference internal" href="#generator-decorator" id="id40">Generator Decorator</a></li>
<li><a class="reference internal" href="#context-managers-in-the-standard-library" id="id41">Context Managers in the Standard Library</a></li>
<li><a class="reference internal" href="#standard-terminology" id="id42">Standard Terminology</a></li>
<li><a class="reference internal" href="#caching-context-managers" id="id43">Caching Context Managers</a></li>
<li><a class="reference internal" href="#resolved-issues" id="id44">Resolved Issues</a></li>
<li><a class="reference internal" href="#rejected-options" id="id45">Rejected Options</a></li>
<li><a class="reference internal" href="#examples" id="id46">Examples</a></li>
<li><a class="reference internal" href="#reference-implementation" id="id47">Reference Implementation</a></li>
<li><a class="reference internal" href="#acknowledgements" id="id48">Acknowledgements</a></li>
<li><a class="reference internal" href="#references" id="id49">References</a></li>
<li><a class="reference internal" href="#copyright" id="id50">Copyright</a></li>
</ul>
</div>
<div class="section" id="abstract">
<h1><a class="toc-backref" href="#id33">Abstract</a></h1>
<p>This PEP adds a new statement &quot;with&quot; to the Python language to make
it possible to factor out standard uses of <tt class="docutils literal">try/finally</tt> statements.</p>
<p>In this PEP, context managers provide <tt class="docutils literal">__enter__()</tt> and <tt class="docutils literal">__exit__()</tt>
methods that are invoked on entry to and exit from the body of the
with statement.</p>
</div>
<div class="section" id="author-s-note">
<h1><a class="toc-backref" href="#id34">Author's Note</a></h1>
<p>This PEP was originally written in first person by Guido, and
subsequently updated by Nick Coghlan to reflect later discussion
on python-dev. Any first person references are from Guido's
original.</p>
<p>Python's alpha release cycle revealed terminology problems in this
PEP and in the associated documentation and implementation <a class="footnote-reference" href="#id30" id="id1">[14]</a>.
The PEP stabilised around the time of the first Python 2.5 beta
release.</p>
<p>Yes, the verb tense is messed up in a few places. We've been
working on this PEP for over a year now, so things that were
originally in the future are now in the past :)</p>
</div>
<div class="section" id="introduction">
<h1><a class="toc-backref" href="#id35">Introduction</a></h1>
<p>After a lot of discussion about <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> and alternatives, I
decided to withdraw <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> and proposed a slight variant on <a class="reference external" href="/dev/peps/pep-0310">PEP
310</a>.  After more discussion, I have added back a mechanism for
raising an exception in a suspended generator using a <tt class="docutils literal">throw()</tt>
method, and a <tt class="docutils literal">close()</tt> method which throws a new GeneratorExit
exception; these additions were first proposed on python-dev in
<a class="footnote-reference" href="#id18" id="id2">[2]</a> and universally approved of.  I'm also changing the keyword to
'with'.</p>
<p>After acceptance of this PEP, the following PEPs were rejected due
to overlap:</p>
<ul class="simple">
<li><a class="reference external" href="/dev/peps/pep-0310">PEP 310</a>, Reliable Acquisition/Release Pairs.  This is the
original with-statement proposal.</li>
<li><a class="reference external" href="/dev/peps/pep-0319">PEP 319</a>, Python Synchronize/Asynchronize Block.  Its use cases
can be covered by the current PEP by providing suitable
with-statement controllers: for 'synchronize' we can use the
&quot;locking&quot; template from example 1; for 'asynchronize' we can use
a similar &quot;unlocking&quot; template.  I don't think having an
&quot;anonymous&quot; lock associated with a code block is all that
important; in fact it may be better to always be explicit about
the mutex being used.</li>
</ul>
<p><a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> and <a class="reference external" href="/dev/peps/pep-0346">PEP 346</a> also overlapped with this PEP, but were
voluntarily withdrawn when this PEP was submitted.</p>
<p>Some discussion of earlier incarnations of this PEP took place on
the Python Wiki <a class="footnote-reference" href="#id19" id="id3">[3]</a>.</p>
</div>
<div class="section" id="motivation-and-summary">
<h1><a class="toc-backref" href="#id36">Motivation and Summary</a></h1>
<p><a class="reference external" href="/dev/peps/pep-0340">PEP 340</a>, Anonymous Block Statements, combined many powerful ideas:
using generators as block templates, adding exception handling and
finalization to generators, and more.  Besides praise it received
a lot of opposition from people who didn't like the fact that it
was, under the covers, a (potential) looping construct.  This
meant that break and continue in a block-statement would break or
continue the block-statement, even if it was used as a non-looping
resource management tool.</p>
<p>But the final blow came when I read Raymond Chen's rant about
flow-control macros <a class="footnote-reference" href="#id17" id="id4">[1]</a>.  Raymond argues convincingly that hiding
flow control in macros makes your code inscrutable, and I find
that his argument applies to Python as well as to C.  I realized
that <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> templates can hide all sorts of control flow; for
example, its example 4 (<tt class="docutils literal">auto_retry()</tt>) catches exceptions and
repeats the block up to three times.</p>
<p>However, the with-statement of <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a> does <strong>not</strong> hide control
flow, in my view: while a finally-suite temporarily suspends the
control flow, in the end, the control flow resumes as if the
finally-suite wasn't there at all.</p>
<p>Remember, <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a> proposes roughly this syntax (the &quot;VAR =&quot; part is
optional):</p>
<pre class="literal-block">
with VAR = EXPR:
    BLOCK
</pre>
<p>which roughly translates into this:</p>
<pre class="literal-block">
VAR = EXPR
VAR.__enter__()
try:
    BLOCK
finally:
    VAR.__exit__()
</pre>
<p>Now consider this example:</p>
<pre class="literal-block">
with f = open(&quot;/etc/passwd&quot;):
    BLOCK1
BLOCK2
</pre>
<p>Here, just as if the first line was &quot;if True&quot; instead, we know
that if <tt class="docutils literal">BLOCK1</tt> completes without an exception, BLOCK2 will be
reached; and if <tt class="docutils literal">BLOCK1</tt> raises an exception or executes a non-local
goto (a break, continue or return), <tt class="docutils literal">BLOCK2</tt> is <strong>not</strong> reached.  The
magic added by the with-statement at the end doesn't affect this.</p>
<p>(You may ask, what if a bug in the <tt class="docutils literal">__exit__()</tt> method causes an
exception?  Then all is lost -- but this is no worse than with
other exceptions; the nature of exceptions is that they can happen
<strong>anywhere</strong>, and you just have to live with that.  Even if you
write bug-free code, a KeyboardInterrupt exception can still cause
it to exit between any two virtual machine opcodes.)</p>
<p>This argument almost led me to endorse <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a>, but I had one idea
left from the <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> euphoria that I wasn't ready to drop: using
generators as &quot;templates&quot; for abstractions like acquiring and
releasing a lock or opening and closing a file is a powerful idea,
as can be seen by looking at the examples in that PEP.</p>
<p>Inspired by a counter-proposal to <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a> by Phillip Eby I tried
to create a decorator that would turn a suitable generator into an
object with the necessary <tt class="docutils literal">__enter__()</tt> and <tt class="docutils literal">__exit__()</tt> methods.
Here I ran into a snag: while it wasn't too hard for the locking
example, it was impossible to do this for the opening example.
The idea was to define the template like this:</p>
<pre class="literal-block">
&#64;contextmanager
def opening(filename):
    f = open(filename)
    try:
        yield f
    finally:
        f.close()
</pre>
<p>and used it like this:</p>
<pre class="literal-block">
with f = opening(filename):
    ...read data from f...
</pre>
<p>The problem is that in <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a>, the result of calling <tt class="docutils literal">EXPR</tt> is
assigned directly to <tt class="docutils literal">VAR</tt>, and then <tt class="docutils literal">VAR</tt>'s <tt class="docutils literal">__exit__()</tt> method is
called upon exit from <tt class="docutils literal">BLOCK1</tt>.  But here, <tt class="docutils literal">VAR</tt> clearly needs to
receive the opened file, and that would mean that <tt class="docutils literal">__exit__()</tt> would
have to be a method on the file.</p>
<p>While this can be solved using a proxy class, this is awkward and
made me realize that a slightly different translation would make
writing the desired decorator a piece of cake: let <tt class="docutils literal">VAR</tt> receive the
result from calling the <tt class="docutils literal">__enter__()</tt> method, and save the value of
<tt class="docutils literal">EXPR</tt> to call its <tt class="docutils literal">__exit__()</tt> method later.  Then the decorator can
return an instance of a wrapper class whose <tt class="docutils literal">__enter__()</tt> method
calls the generator's <tt class="docutils literal">next()</tt> method and returns whatever <tt class="docutils literal">next()</tt>
returns; the wrapper instance's <tt class="docutils literal">__exit__()</tt> method calls <tt class="docutils literal">next()</tt>
again but expects it to raise StopIteration.  (Details below in
the section Optional Generator Decorator.)</p>
<p>So now the final hurdle was that the <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a> syntax:</p>
<pre class="literal-block">
with VAR = EXPR:
    BLOCK1
</pre>
<p>would be deceptive, since <tt class="docutils literal">VAR</tt> does <strong>not</strong> receive the value of
<tt class="docutils literal">EXPR</tt>.  Borrowing from <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a>, it was an easy step to:</p>
<pre class="literal-block">
with EXPR as VAR:
    BLOCK1
</pre>
<p>Additional discussion showed that people really liked being able
to &quot;see&quot; the exception in the generator, even if it was only to
log it; the generator is not allowed to yield another value, since
the with-statement should not be usable as a loop (raising a
different exception is marginally acceptable).  To enable this, a
new <tt class="docutils literal">throw()</tt> method for generators is proposed, which takes one to
three arguments representing an exception in the usual fashion
(type, value, traceback) and raises it at the point where the
generator is suspended.</p>
<p>Once we have this, it is a small step to proposing another
generator method, <tt class="docutils literal">close()</tt>, which calls <tt class="docutils literal">throw()</tt> with a special
exception, <tt class="docutils literal">GeneratorExit</tt>.  This tells the generator to exit, and
from there it's another small step to proposing that <tt class="docutils literal">close()</tt> be
called automatically when the generator is garbage-collected.</p>
<p>Then, finally, we can allow a yield-statement inside a try-finally
statement, since we can now guarantee that the finally-clause will
(eventually) be executed.  The usual cautions about finalization
apply -- the process may be terminated abruptly without finalizing
any objects, and objects may be kept alive forever by cycles or
memory leaks in the application (as opposed to cycles or leaks in
the Python implementation, which are taken care of by GC).</p>
<p>Note that we're not guaranteeing that the finally-clause is
executed immediately after the generator object becomes unused,
even though this is how it will work in CPython.  This is similar
to auto-closing files: while a reference-counting implementation
like CPython deallocates an object as soon as the last reference
to it goes away, implementations that use other GC algorithms do
not make the same guarantee.  This applies to Jython, IronPython,
and probably to Python running on Parrot.</p>
<p>(The details of the changes made to generators can now be found in
<a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> rather than in the current PEP)</p>
</div>
<div class="section" id="use-cases">
<h1><a class="toc-backref" href="#id37">Use Cases</a></h1>
<p>See the Examples section near the end.</p>
</div>
<div class="section" id="specification-the-with-statement">
<h1><a class="toc-backref" href="#id38">Specification: The 'with' Statement</a></h1>
<p>A new statement is proposed with the syntax:</p>
<pre class="literal-block">
with EXPR as VAR:
    BLOCK
</pre>
<p>Here, 'with' and 'as' are new keywords; <tt class="docutils literal">EXPR</tt> is an arbitrary
expression (but not an expression-list) and <tt class="docutils literal">VAR</tt> is a single
assignment target.  It can <strong>not</strong> be a comma-separated sequence of
variables, but it <strong>can</strong> be a <strong>parenthesized</strong> comma-separated
sequence of variables.  (This restriction makes a future extension
possible of the syntax to have multiple comma-separated resources,
each with its own optional as-clause.)</p>
<p>The &quot;as VAR&quot; part is optional.</p>
<p>The translation of the above statement is:</p>
<pre class="literal-block">
mgr = (EXPR)
exit = type(mgr).__exit__  # Not calling it yet
value = type(mgr).__enter__(mgr)
exc = True
try:
    try:
        VAR = value  # Only if &quot;as VAR&quot; is present
        BLOCK
    except:
        # The exceptional case is handled here
        exc = False
        if not exit(mgr, *sys.exc_info()):
            raise
        # The exception is swallowed if exit() returns true
finally:
    # The normal and non-local-goto cases are handled here
    if exc:
        exit(mgr, None, None, None)
</pre>
<p>Here, the lowercase variables (mgr, exit, value, exc) are internal
variables and not accessible to the user; they will most likely be
implemented as special registers or stack positions.</p>
<p>The details of the above translation are intended to prescribe the
exact semantics.  If either of the relevant methods are not found
as expected, the interpreter will raise <tt class="docutils literal">AttributeError</tt>, in the
order that they are tried (<tt class="docutils literal">__exit__</tt>, <tt class="docutils literal">__enter__</tt>).
Similarly, if any of the calls raises an exception, the effect is
exactly as it would be in the above code.  Finally, if <tt class="docutils literal">BLOCK</tt>
contains a break, continue or return statement, the <tt class="docutils literal">__exit__()</tt>
method is called with three None arguments just as if <tt class="docutils literal">BLOCK</tt>
completed normally.  (I.e. these &quot;pseudo-exceptions&quot; are not seen
as exceptions by <tt class="docutils literal">__exit__()</tt>.)</p>
<p>If the &quot;as VAR&quot; part of the syntax is omitted, the &quot;VAR =&quot; part of
the translation is omitted (but <tt class="docutils literal">mgr.__enter__()</tt> is still called).</p>
<p>The calling convention for <tt class="docutils literal">mgr.__exit__()</tt> is as follows.  If the
finally-suite was reached through normal completion of <tt class="docutils literal">BLOCK</tt> or
through a non-local goto (a break, continue or return statement in
<tt class="docutils literal">BLOCK</tt>), <tt class="docutils literal">mgr.__exit__()</tt> is called with three <tt class="docutils literal">None</tt> arguments.  If
the finally-suite was reached through an exception raised in
<tt class="docutils literal">BLOCK</tt>, <tt class="docutils literal">mgr.__exit__()</tt> is called with three arguments representing
the exception type, value, and traceback.</p>
<p>IMPORTANT: if <tt class="docutils literal">mgr.__exit__()</tt> returns a &quot;true&quot; value, the exception
is &quot;swallowed&quot;.  That is, if it returns &quot;true&quot;, execution
continues at the next statement after the with-statement, even if
an exception happened inside the with-statement.  However, if the
with-statement was left via a non-local goto (break, continue or
return), this non-local return is resumed when <tt class="docutils literal">mgr.__exit__()</tt>
returns regardless of the return value.  The motivation for this
detail is to make it possible for <tt class="docutils literal">mgr.__exit__()</tt> to swallow
exceptions, without making it too easy (since the default return
value, <tt class="docutils literal">None</tt>, is false and this causes the exception to be
re-raised).  The main use case for swallowing exceptions is to
make it possible to write the <tt class="docutils literal">&#64;contextmanager</tt> decorator so
that a try/except block in a decorated generator behaves exactly
as if the body of the generator were expanded in-line at the place
of the with-statement.</p>
<p>The motivation for passing the exception details to <tt class="docutils literal">__exit__()</tt>, as
opposed to the argument-less <tt class="docutils literal">__exit__()</tt> from <a class="reference external" href="/dev/peps/pep-0310">PEP 310</a>, was given by
the <tt class="docutils literal">transactional()</tt> use case, example 3 below.  The template in
that example must commit or roll back the transaction depending on
whether an exception occurred or not.  Rather than just having a
boolean flag indicating whether an exception occurred, we pass the
complete exception information, for the benefit of an
exception-logging facility for example.  Relying on <tt class="docutils literal">sys.exc_info()</tt>
to get at the exception information was rejected; <tt class="docutils literal">sys.exc_info()</tt>
has very complex semantics and it is perfectly possible that it
returns the exception information for an exception that was caught
ages ago.  It was also proposed to add an additional boolean to
distinguish between reaching the end of <tt class="docutils literal">BLOCK</tt> and a non-local
goto.  This was rejected as too complex and unnecessary; a
non-local goto should be considered unexceptional for the purposes
of a database transaction roll-back decision.</p>
<p>To facilitate chaining of contexts in Python code that directly
manipulates context managers, <tt class="docutils literal">__exit__()</tt> methods  should <strong>not</strong>
re-raise the error that is passed in to them. It is always the
responsibility of the <strong>caller</strong> of the <tt class="docutils literal">__exit__()</tt> method to do any
reraising in that case.</p>
<p>That way, if the caller needs to tell whether the <tt class="docutils literal">__exit__()</tt>
invocation <strong>failed</strong> (as opposed to successfully cleaning up before
propagating the original error), it can do so.</p>
<p>If <tt class="docutils literal">__exit__()</tt> returns without an error, this can then be
interpreted as success of the <tt class="docutils literal">__exit__()</tt> method itself (regardless
of whether or not the original error is to be propagated or
suppressed).</p>
<p>However, if <tt class="docutils literal">__exit__()</tt> propagates an exception to its caller, this
means that <tt class="docutils literal">__exit__()</tt> <strong>itself</strong> has failed.  Thus, <tt class="docutils literal">__exit__()</tt>
methods should avoid raising errors unless they have actually
failed.  (And allowing the original error to proceed isn't a
failure.)</p>
</div>
<div class="section" id="transition-plan">
<h1><a class="toc-backref" href="#id39">Transition Plan</a></h1>
<p>In Python 2.5, the new syntax will only be recognized if a future
statement is present:</p>
<pre class="literal-block">
from __future__ import with_statement
</pre>
<p>This will make both 'with' and 'as' keywords.  Without the future
statement, using 'with' or 'as' as an identifier will cause a
Warning to be issued to stderr.</p>
<p>In Python 2.6, the new syntax will always be recognized; 'with'
and 'as' are always keywords.</p>
</div>
<div class="section" id="generator-decorator">
<h1><a class="toc-backref" href="#id40">Generator Decorator</a></h1>
<p>With <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> accepted, it is possible to write a decorator
that makes it possible to use a generator that yields exactly once
to control a with-statement.  Here's a sketch of such a decorator:</p>
<pre class="literal-block">
class GeneratorContextManager(object):

   def __init__(self, gen):
       self.gen = gen

   def __enter__(self):
       try:
           return self.gen.next()
       except StopIteration:
           raise RuntimeError(&quot;generator didn't yield&quot;)

   def __exit__(self, type, value, traceback):
       if type is None:
           try:
               self.gen.next()
           except StopIteration:
               return
           else:
               raise RuntimeError(&quot;generator didn't stop&quot;)
       else:
           try:
               self.gen.throw(type, value, traceback)
               raise RuntimeError(&quot;generator didn't stop after throw()&quot;)
           except StopIteration:
               return True
           except:
               # only re-raise if it's *not* the exception that was
               # passed to throw(), because __exit__() must not raise
               # an exception unless __exit__() itself failed.  But
               # throw() has to raise the exception to signal
               # propagation, so this fixes the impedance mismatch
               # between the throw() protocol and the __exit__()
               # protocol.
               #
               if sys.exc_info()[1] is not value:
                   raise

def contextmanager(func):
   def helper(*args, **kwds):
       return GeneratorContextManager(func(*args, **kwds))
   return helper
</pre>
<p>This decorator could be used as follows:</p>
<pre class="literal-block">
&#64;contextmanager
def opening(filename):
   f = open(filename) # IOError is untouched by GeneratorContext
   try:
       yield f
   finally:
       f.close() # Ditto for errors here (however unlikely)
</pre>
<p>A robust implementation of this decorator will be made
part of the standard library.</p>
</div>
<div class="section" id="context-managers-in-the-standard-library">
<h1><a class="toc-backref" href="#id41">Context Managers in the Standard Library</a></h1>
<p>It would be possible to endow certain objects, like files,
sockets, and locks, with <tt class="docutils literal">__enter__()</tt> and <tt class="docutils literal">__exit__()</tt> methods so
that instead of writing:</p>
<pre class="literal-block">
with locking(myLock):
    BLOCK
</pre>
<p>one could write simply:</p>
<pre class="literal-block">
with myLock:
    BLOCK
</pre>
<p>I think we should be careful with this; it could lead to mistakes
like:</p>
<pre class="literal-block">
f = open(filename)
with f:
    BLOCK1
with f:
    BLOCK2
</pre>
<p>which does not do what one might think (f is closed before <tt class="docutils literal">BLOCK2</tt>
is entered).</p>
<p>OTOH such mistakes are easily diagnosed; for example, the
generator context decorator above raises <tt class="docutils literal">RuntimeError</tt> when a
second  with-statement calls <tt class="docutils literal">f.__enter__()</tt> again. A similar error
can be raised if <tt class="docutils literal">__enter__</tt> is invoked on a closed file object.</p>
<p>For Python 2.5, the following types have been identified as
context managers:</p>
<pre class="literal-block">
- file
- thread.LockType
- threading.Lock
- threading.RLock
- threading.Condition
- threading.Semaphore
- threading.BoundedSemaphore
</pre>
<p>A context manager will also be added to the decimal module to
support using a local decimal arithmetic context within the body
of a with statement, automatically restoring the original context
when the with statement is exited.</p>
</div>
<div class="section" id="standard-terminology">
<h1><a class="toc-backref" href="#id42">Standard Terminology</a></h1>
<p>This PEP proposes that the protocol consisting of the <tt class="docutils literal">__enter__()</tt>
and <tt class="docutils literal">__exit__()</tt> methods be known as the &quot;context management protocol&quot;,
and that objects that implement that protocol be known as &quot;context
managers&quot;. <a class="footnote-reference" href="#id20" id="id5">[4]</a></p>
<p>The expression immediately following the with keyword in the
statement is a &quot;context expression&quot; as that expression provides the
main clue as to the runtime environment the context manager
establishes for the duration of the statement body.</p>
<p>The code in the body of the with statement and the variable name
(or names) after the as keyword don't really have special terms at
this point in time. The general terms &quot;statement body&quot; and &quot;target
list&quot; can be used, prefixing with &quot;with&quot; or &quot;with statement&quot; if the
terms would otherwise be unclear.</p>
<p>Given the existence of objects such as the decimal module's
arithmetic context, the term &quot;context&quot; is unfortunately ambiguous.
If necessary, it can be made more specific by using the terms
&quot;context manager&quot; for the concrete object created by the context
expression and &quot;runtime context&quot; or (preferably) &quot;runtime
environment&quot; for the actual state modifications made by the context
manager. When simply discussing use of the with statement, the
ambiguity shouldn't matter too much as the context expression fully
defines the changes made to the runtime environment.
The distinction is more important when discussing the mechanics of
the with statement itself and how to go about actually implementing
context managers.</p>
</div>
<div class="section" id="caching-context-managers">
<h1><a class="toc-backref" href="#id43">Caching Context Managers</a></h1>
<p>Many context managers (such as files and generator-based contexts)
will be single-use objects. Once the <tt class="docutils literal">__exit__()</tt> method has been
called, the context manager will no longer be in a usable state
(e.g. the file has been closed, or the underlying generator has
finished execution).</p>
<p>Requiring a fresh manager object for each with statement is the
easiest way to avoid problems with multi-threaded code and nested
with statements trying to use the same context manager. It isn't
coincidental that all of the standard library context managers
that support reuse come from the threading module - they're all
already designed to deal with the problems created by threaded
and nested usage.</p>
<p>This means that in order to save a context manager with particular
initialisation arguments to be used in multiple with statements, it
will typically be necessary to store it in a zero-argument callable
that is then called in the context expression of each statement
rather than caching the context manager directly.</p>
<p>When this restriction does not apply, the documentation of the
affected context manager should make that clear.</p>
</div>
<div class="section" id="resolved-issues">
<h1><a class="toc-backref" href="#id44">Resolved Issues</a></h1>
<p>The following issues were resolved by BDFL approval (and a lack
of any major objections on python-dev).</p>
<ol class="arabic">
<li><p class="first">What exception should <tt class="docutils literal">GeneratorContextManager</tt> raise when the
underlying generator-iterator misbehaves? The following quote is
the reason behind Guido's choice of <tt class="docutils literal">RuntimeError</tt> for both this
and for the generator <tt class="docutils literal">close()</tt> method in <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> (from <a class="footnote-reference" href="#id24" id="id6">[8]</a>):</p>
<p>&quot;I'd rather not introduce a new exception class just for this
purpose, since it's not an exception that I want people to catch:
I want it to turn into a traceback which is seen by the
programmer who then fixes the code.  So now I believe they
should both raise <tt class="docutils literal">RuntimeError</tt>.
There are some precedents for that: it's raised by the core
Python code in situations where endless recursion is detected,
and for uninitialized objects (and for a variety of
miscellaneous conditions).&quot;</p>
</li>
<li><p class="first">It is fine to raise <tt class="docutils literal">AttributeError</tt> instead of <tt class="docutils literal">TypeError</tt> if the
relevant methods aren't present on a class involved in a with
statement. The fact that the abstract object C API raises
<tt class="docutils literal">TypeError</tt> rather than <tt class="docutils literal">AttributeError</tt> is an accident of history,
rather than a deliberate design decision <a class="footnote-reference" href="#id27" id="id7">[11]</a>.</p>
</li>
<li><p class="first">Objects with <tt class="docutils literal">__enter__/__exit__</tt> methods are called &quot;context
managers&quot; and the decorator to convert a generator function
into a context manager factory is <tt class="docutils literal">contextlib.contextmanager</tt>.
There were some other suggestions <a class="footnote-reference" href="#id32" id="id8">[16]</a> during the 2.5 release
cycle but no compelling arguments for switching away from the
terms that had been used in the PEP implementation were made.</p>
</li>
</ol>
</div>
<div class="section" id="rejected-options">
<h1><a class="toc-backref" href="#id45">Rejected Options</a></h1>
<p>For several months, the PEP prohibited suppression of exceptions
in order to avoid hidden flow control. Implementation
revealed this to be a right royal pain, so Guido restored the
ability <a class="footnote-reference" href="#id29" id="id9">[13]</a>.</p>
<p>Another aspect of the PEP that caused no end of questions and
terminology debates was providing a <tt class="docutils literal">__context__()</tt> method that
was analogous to an iterable's <tt class="docutils literal">__iter__()</tt> method <a class="footnote-reference" href="#id21" id="id10">[5]</a> <a class="footnote-reference" href="#id23" id="id11">[7]</a> <a class="footnote-reference" href="#id25" id="id12">[9]</a>.
The ongoing problems <a class="footnote-reference" href="#id26" id="id13">[10]</a> <a class="footnote-reference" href="#id29" id="id14">[13]</a> with explaining what it was and why
it was and how it was meant to work eventually lead to Guido
killing the concept outright <a class="footnote-reference" href="#id31" id="id15">[15]</a> (and there was much rejoicing!).</p>
<p>The notion of using the <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> generator API directly to define
the with statement was also briefly entertained <a class="footnote-reference" href="#id22" id="id16">[6]</a>, but quickly
dismissed as making it too difficult to write non-generator
based context managers.</p>
</div>
<div class="section" id="examples">
<h1><a class="toc-backref" href="#id46">Examples</a></h1>
<p>The generator based examples rely on <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a>. Also, some of the
examples are unnecessary in practice, as the appropriate objects,
such as <tt class="docutils literal">threading.RLock</tt>, are able to be used directly in with
statements.</p>
<p>The tense used in the names of the example contexts is not
arbitrary. Past tense (&quot;-ed&quot;) is used when the name refers to an
action which is done in the <tt class="docutils literal">__enter__</tt> method and undone in the
<tt class="docutils literal">__exit__</tt> method. Progressive tense (&quot;-ing&quot;) is used when the name
refers to an action which is to be done in the <tt class="docutils literal">__exit__</tt> method.</p>
<ol class="arabic">
<li><p class="first">A template for ensuring that a lock, acquired at the start of a
block, is released when the block is left:</p>
<pre class="literal-block">
&#64;contextmanager
def locked(lock):
    lock.acquire()
    try:
        yield
    finally:
        lock.release()
</pre>
<p>Used as follows:</p>
<pre class="literal-block">
with locked(myLock):
    # Code here executes with myLock held.  The lock is
    # guaranteed to be released when the block is left (even
    # if via return or by an uncaught exception).
</pre>
</li>
<li><p class="first">A template for opening a file that ensures the file is closed
when the block is left:</p>
<pre class="literal-block">
&#64;contextmanager
def opened(filename, mode=&quot;r&quot;):
    f = open(filename, mode)
    try:
        yield f
    finally:
        f.close()
</pre>
<p>Used as follows:</p>
<pre class="literal-block">
with opened(&quot;/etc/passwd&quot;) as f:
    for line in f:
        print line.rstrip()
</pre>
</li>
<li><p class="first">A template for committing or rolling back a database
transaction:</p>
<pre class="literal-block">
&#64;contextmanager
def transaction(db):
    db.begin()
    try:
        yield None
    except:
        db.rollback()
        raise
    else:
        db.commit()
</pre>
</li>
<li><p class="first">Example 1 rewritten without a generator:</p>
<pre class="literal-block">
class locked:
   def __init__(self, lock):
       self.lock = lock
   def __enter__(self):
       self.lock.acquire()
   def __exit__(self, type, value, tb):
       self.lock.release()
</pre>
<p>(This example is easily modified to implement the other
relatively stateless examples; it shows that it is easy to avoid
the need for a generator if no special state needs to be
preserved.)</p>
</li>
<li><p class="first">Redirect stdout temporarily:</p>
<pre class="literal-block">
&#64;contextmanager
def stdout_redirected(new_stdout):
    save_stdout = sys.stdout
    sys.stdout = new_stdout
    try:
        yield None
    finally:
        sys.stdout = save_stdout
</pre>
<p>Used as follows:</p>
<pre class="literal-block">
with opened(filename, &quot;w&quot;) as f:
    with stdout_redirected(f):
        print &quot;Hello world&quot;
</pre>
<p>This isn't thread-safe, of course, but neither is doing this
same dance manually.  In single-threaded programs (for example,
in scripts) it is a popular way of doing things.</p>
</li>
<li><p class="first">A variant on <tt class="docutils literal">opened()</tt> that also returns an error condition:</p>
<pre class="literal-block">
&#64;contextmanager
def opened_w_error(filename, mode=&quot;r&quot;):
    try:
        f = open(filename, mode)
    except IOError, err:
        yield None, err
    else:
        try:
            yield f, None
        finally:
            f.close()
</pre>
<p>Used as follows:</p>
<pre class="literal-block">
with opened_w_error(&quot;/etc/passwd&quot;, &quot;a&quot;) as (f, err):
    if err:
        print &quot;IOError:&quot;, err
    else:
        f.write(&quot;guido::0:0::/:/bin/sh\n&quot;)
</pre>
</li>
<li><p class="first">Another useful example would be an operation that blocks
signals.  The use could be like this:</p>
<pre class="literal-block">
import signal

with signal.blocked():
    # code executed without worrying about signals
</pre>
<p>An optional argument might be a list of signals to be blocked;
by default all signals are blocked.  The implementation is left
as an exercise to the reader.</p>
</li>
<li><p class="first">Another use for this feature is the Decimal context.  Here's a
simple example, after one posted by Michael Chermside:</p>
<pre class="literal-block">
import decimal

&#64;contextmanager
def extra_precision(places=2):
    c = decimal.getcontext()
    saved_prec = c.prec
    c.prec += places
    try:
        yield None
    finally:
        c.prec = saved_prec
</pre>
<p>Sample usage (adapted from the Python Library Reference):</p>
<pre class="literal-block">
def sin(x):
    &quot;Return the sine of x as measured in radians.&quot;
    with extra_precision():
        i, lasts, s, fact, num, sign = 1, 0, x, 1, x, 1
        while s != lasts:
            lasts = s
            i += 2
            fact *= i * (i-1)
            num *= x * x
            sign *= -1
            s += num / fact * sign
    # The &quot;+s&quot; rounds back to the original precision,
    # so this must be outside the with-statement:
    return +s
</pre>
</li>
<li><p class="first">Here's a simple context manager for the decimal module:</p>
<pre class="literal-block">
&#64;contextmanager
def localcontext(ctx=None):
    &quot;&quot;&quot;Set a new local decimal context for the block&quot;&quot;&quot;
    # Default to using the current context
    if ctx is None:
        ctx = getcontext()
    # We set the thread context to a copy of this context
    # to ensure that changes within the block are kept
    # local to the block.
    newctx = ctx.copy()
    oldctx = decimal.getcontext()
    decimal.setcontext(newctx)
    try:
        yield newctx
    finally:
        # Always restore the original context
        decimal.setcontext(oldctx)
</pre>
<p>Sample usage:</p>
<pre class="literal-block">
from decimal import localcontext, ExtendedContext

def sin(x):
    with localcontext() as ctx:
        ctx.prec += 2
        # Rest of sin calculation algorithm
        # uses a precision 2 greater than normal
    return +s # Convert result to normal precision

def sin(x):
    with localcontext(ExtendedContext):
        # Rest of sin calculation algorithm
        # uses the Extended Context from the
        # General Decimal Arithmetic Specification
    return +s # Convert result to normal context
</pre>
</li>
<li><p class="first">A generic &quot;object-closing&quot; context manager:</p>
<pre class="literal-block">
class closing(object):
    def __init__(self, obj):
        self.obj = obj
    def __enter__(self):
        return self.obj
    def __exit__(self, *exc_info):
        try:
            close_it = self.obj.close
        except AttributeError:
            pass
        else:
            close_it()
</pre>
<p>This can be used to deterministically close anything with a
close method, be it file, generator, or something else. It
can even be used when the object isn't guaranteed to require
closing (e.g., a function that accepts an arbitrary
iterable):</p>
<pre class="literal-block">
# emulate opening():
with closing(open(&quot;argument.txt&quot;)) as contradiction:
   for line in contradiction:
       print line

# deterministically finalize an iterator:
with closing(iter(data_source)) as data:
   for datum in data:
       process(datum)
</pre>
<p>(Python 2.5's contextlib module contains a version
of this context manager)</p>
</li>
<li><p class="first"><a class="reference external" href="/dev/peps/pep-0319">PEP 319</a> gives a use case for also having a <tt class="docutils literal">released()</tt>
context to temporarily release a previously acquired lock;
this can be written very similarly to the locked context
manager above by swapping the <tt class="docutils literal">acquire()</tt> and <tt class="docutils literal">release()</tt> calls:</p>
<pre class="literal-block">
class released:
  def __init__(self, lock):
      self.lock = lock
  def __enter__(self):
      self.lock.release()
  def __exit__(self, type, value, tb):
      self.lock.acquire()
</pre>
<p>Sample usage:</p>
<pre class="literal-block">
with my_lock:
    # Operations with the lock held
    with released(my_lock):
        # Operations without the lock
        # e.g. blocking I/O
    # Lock is held again here
</pre>
</li>
<li><p class="first">A &quot;nested&quot; context manager that automatically nests the
supplied contexts from left-to-right to avoid excessive
indentation:</p>
<pre class="literal-block">
&#64;contextmanager
def nested(*contexts):
    exits = []
    vars = []
    try:
        try:
            for context in contexts:
                mgr = context.__context__()
                exit = mgr.__exit__
                enter = mgr.__enter__
                vars.append(enter())
                exits.append(exit)
            yield vars
        except:
            exc = sys.exc_info()
        else:
            exc = (None, None, None)
    finally:
        while exits:
            exit = exits.pop()
            try:
                exit(*exc)
            except:
                exc = sys.exc_info()
            else:
                exc = (None, None, None)
        if exc != (None, None, None):
            # sys.exc_info() may have been
            # changed by one of the exit methods
            # so provide explicit exception info
            raise exc[0], exc[1], exc[2]
</pre>
<p>Sample usage:</p>
<pre class="literal-block">
with nested(a, b, c) as (x, y, z):
    # Perform operation
</pre>
<p>Is equivalent to:</p>
<pre class="literal-block">
with a as x:
    with b as y:
        with c as z:
            # Perform operation
</pre>
<p>(Python 2.5's contextlib module contains a version
of this context manager)</p>
</li>
</ol>
</div>
<div class="section" id="reference-implementation">
<h1><a class="toc-backref" href="#id47">Reference Implementation</a></h1>
<p>This PEP was first accepted by Guido at his EuroPython
keynote, 27 June 2005.
It was accepted again later, with <tt class="docutils literal">the __context__</tt> method added.
The PEP was implemented in Subversion for Python 2.5a1
The <tt class="docutils literal">__context__()</tt> method will be removed in Python 2.5a3</p>
</div>
<div class="section" id="acknowledgements">
<h1><a class="toc-backref" href="#id48">Acknowledgements</a></h1>
<p>Many people contributed to the ideas and concepts in this PEP,
including all those mentioned in the acknowledgements for <a class="reference external" href="/dev/peps/pep-0340">PEP 340</a>
and <a class="reference external" href="/dev/peps/pep-0346">PEP 346</a>.</p>
<p>Additional thanks goes to (in no meaningful order): Paul Moore,
Phillip J. Eby, Greg Ewing, Jason Orendorff, Michael Hudson,
Raymond Hettinger, Walter Dörwald, Aahz, Georg Brandl, Terry Reedy,
A.M. Kuchling, Brett Cannon, and all those that participated in the
discussions on python-dev.</p>
</div>
<div class="section" id="references">
<h1><a class="toc-backref" href="#id49">References</a></h1>
<table class="docutils footnote" frame="void" id="id17" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id4">[1]</a></td><td>Raymond Chen's article on hidden flow control
<a class="reference external" href="http://blogs.msdn.com/oldnewthing/archive/2005/01/06/347666.aspx">http://blogs.msdn.com/oldnewthing/archive/2005/01/06/347666.aspx</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id18" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id2">[2]</a></td><td>Guido suggests some generator changes that ended up in <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a>
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-May/053885.html">https://mail.python.org/pipermail/python-dev/2005-May/053885.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id19" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id3">[3]</a></td><td>Wiki discussion of <a class="reference external" href="/dev/peps/pep-0343">PEP 343</a>
<a class="reference external" href="http://wiki.python.org/moin/WithStatement">http://wiki.python.org/moin/WithStatement</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id20" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id5">[4]</a></td><td>Early draft of some documentation for the with statement
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-July/054658.html">https://mail.python.org/pipermail/python-dev/2005-July/054658.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id21" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id10">[5]</a></td><td>Proposal to add the __with__ method
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/056947.html">https://mail.python.org/pipermail/python-dev/2005-October/056947.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id22" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id16">[6]</a></td><td>Proposal to use the <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> enhanced generator API directly
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/056969.html">https://mail.python.org/pipermail/python-dev/2005-October/056969.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id23" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id11">[7]</a></td><td>Guido lets me (Nick Coghlan) talk him into a bad idea ;)
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/057018.html">https://mail.python.org/pipermail/python-dev/2005-October/057018.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id24" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id6">[8]</a></td><td>Guido raises some exception handling questions
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-June/054064.html">https://mail.python.org/pipermail/python-dev/2005-June/054064.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id25" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id12">[9]</a></td><td>Guido answers some questions about the __context__ method
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/057520.html">https://mail.python.org/pipermail/python-dev/2005-October/057520.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id26" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id13">[10]</a></td><td>Guido answers more questions about the __context__ method
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/057535.html">https://mail.python.org/pipermail/python-dev/2005-October/057535.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id27" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id7">[11]</a></td><td>Guido says AttributeError is fine for missing special methods
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2005-October/057625.html">https://mail.python.org/pipermail/python-dev/2005-October/057625.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id28" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[12]</td><td>Original <a class="reference external" href="/dev/peps/pep-0342">PEP 342</a> implementation patch
<a class="reference external" href="http://sourceforge.net/tracker/index.php?func=detail&amp;aid=1223381&amp;group_id=5470&amp;atid=305470">http://sourceforge.net/tracker/index.php?func=detail&amp;aid=1223381&amp;group_id=5470&amp;atid=305470</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id29" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[13]</td><td><em>(<a class="fn-backref" href="#id9">1</a>, <a class="fn-backref" href="#id14">2</a>)</em> Guido restores the ability to suppress exceptions
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2006-February/061909.html">https://mail.python.org/pipermail/python-dev/2006-February/061909.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id30" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[14]</a></td><td>A simple question kickstarts a thorough review of <a class="reference external" href="/dev/peps/pep-0343">PEP 343</a>
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2006-April/063859.html">https://mail.python.org/pipermail/python-dev/2006-April/063859.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id31" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id15">[15]</a></td><td>Guido kills the __context__() method
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2006-April/064632.html">https://mail.python.org/pipermail/python-dev/2006-April/064632.html</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id32" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id8">[16]</a></td><td>Proposal to use 'context guard' instead of 'context manager'
<a class="reference external" href="https://mail.python.org/pipermail/python-dev/2006-May/064676.html">https://mail.python.org/pipermail/python-dev/2006-May/064676.html</a></td></tr>
</tbody>
</table>
</div>
<div class="section" id="copyright">
<h1><a class="toc-backref" href="#id50">Copyright</a></h1>
<p>This document has been placed in the public domain.</p>
<!-- Local Variables:
mode: indented-text
indent-tabs-mode: nil
sentence-end-double-space: t
fill-column: 70
coding: utf-8
End: -->
</div>

