<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
PEP, see http://www.python.org/dev/peps/pep-0001 for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->
<table class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">PEP:</th><td class="field-body">522</td>
</tr>
<tr class="field"><th class="field-name">Title:</th><td class="field-body">Allow BlockingIOError in security sensitive APIs</td>
</tr>
<tr class="field"><th class="field-name">Version:</th><td class="field-body">$Revision$</td>
</tr>
<tr class="field"><th class="field-name">Last-Modified:</th><td class="field-body"><a class="reference external" href="https://hg.python.org/peps/file/tip/pep-0522.txt">$Date$</a></td>
</tr>
<tr class="field"><th class="field-name">Author:</th><td class="field-body">Nick Coghlan &lt;ncoghlan&#32;&#97;t&#32;gmail.com&gt;, Nathaniel J. Smith &lt;njs&#32;&#97;t&#32;pobox.com&gt;</td>
</tr>
<tr class="field"><th class="field-name">Status:</th><td class="field-body">Rejected</td>
</tr>
<tr class="field"><th class="field-name">Type:</th><td class="field-body">Standards Track</td>
</tr>
<tr class="field"><th class="field-name">Content-Type:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0012">text/x-rst</a></td>
</tr>
<tr class="field"><th class="field-name">Requires:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0506">506</a></td>
</tr>
<tr class="field"><th class="field-name">Created:</th><td class="field-body">16 June 2016</td>
</tr>
<tr class="field"><th class="field-name">Python-Version:</th><td class="field-body">3.6</td>
</tr>
<tr class="field"><th class="field-name">Resolution:</th><td class="field-body"><a class="reference external" href="https://mail.python.org/pipermail/security-sig/2016-August/000101.html">https://mail.python.org/pipermail/security-sig/2016-August/000101.html</a></td>
</tr>
</tbody>
</table>
<hr />
<div class="contents topic" id="contents">
<p class="topic-title first">Contents</p>
<ul class="simple">
<li><a class="reference internal" href="#abstract" id="id23">Abstract</a></li>
<li><a class="reference internal" href="#relationship-with-other-peps" id="id24">Relationship with other PEPs</a></li>
<li><a class="reference internal" href="#pep-rejection" id="id25">PEP Rejection</a></li>
<li><a class="reference internal" href="#changes-independent-of-this-pep" id="id26">Changes independent of this PEP</a></li>
<li><a class="reference internal" href="#proposal" id="id27">Proposal</a><ul>
<li><a class="reference internal" href="#changing-os-urandom-on-platforms-with-the-getrandom-system-call" id="id28">Changing <tt class="docutils literal">os.urandom()</tt> on platforms with the getrandom() system call</a></li>
<li><a class="reference internal" href="#adding-secrets-wait-for-system-rng" id="id29">Adding <tt class="docutils literal">secrets.wait_for_system_rng()</tt></a></li>
<li><a class="reference internal" href="#limitations-on-scope" id="id30">Limitations on scope</a></li>
</ul>
</li>
<li><a class="reference internal" href="#rationale" id="id31">Rationale</a><ul>
<li><a class="reference internal" href="#ensuring-the-secrets-module-implicitly-blocks-when-needed" id="id32">Ensuring the <tt class="docutils literal">secrets</tt> module implicitly blocks when needed</a></li>
<li><a class="reference internal" href="#raising-blockingioerror-in-os-urandom-on-linux" id="id33">Raising <tt class="docutils literal">BlockingIOError</tt> in <tt class="docutils literal">os.urandom()</tt> on Linux</a></li>
<li><a class="reference internal" href="#making-secrets-wait-for-system-rng-public" id="id34">Making <tt class="docutils literal">secrets.wait_for_system_rng()</tt> public</a></li>
</ul>
</li>
<li><a class="reference internal" href="#backwards-compatibility-impact-assessment" id="id35">Backwards Compatibility Impact Assessment</a><ul>
<li><a class="reference internal" href="#unaffected-applications" id="id36">Unaffected Applications</a></li>
<li><a class="reference internal" href="#affected-security-sensitive-applications" id="id37">Affected security sensitive applications</a></li>
<li><a class="reference internal" href="#affected-non-security-sensitive-applications" id="id38">Affected non-security sensitive applications</a></li>
</ul>
</li>
<li><a class="reference internal" href="#additional-background" id="id39">Additional Background</a><ul>
<li><a class="reference internal" href="#why-propose-this-now" id="id40">Why propose this now?</a></li>
<li><a class="reference internal" href="#the-cross-platform-behaviour-of-os-urandom" id="id41">The cross-platform behaviour of <tt class="docutils literal">os.urandom()</tt></a></li>
<li><a class="reference internal" href="#problems-with-the-behaviour-of-dev-urandom-on-linux" id="id42">Problems with the behaviour of <tt class="docutils literal">/dev/urandom</tt> on Linux</a></li>
<li><a class="reference internal" href="#consequences-of-getrandom-availability-for-python" id="id43">Consequences of <tt class="docutils literal">getrandom()</tt> availability for Python</a></li>
</ul>
</li>
<li><a class="reference internal" href="#references" id="id44">References</a></li>
<li><a class="reference internal" href="#copyright" id="id45">Copyright</a></li>
</ul>
</div>
<div class="section" id="abstract">
<h1><a class="toc-backref" href="#id23">Abstract</a></h1>
<p>A number of APIs in the standard library that return random values nominally
suitable for use in security sensitive operations currently have an obscure
operating system dependent failure mode that allows them to return values that
are not, in fact, suitable for such operations.</p>
<p>This is due to some operating system kernels (most notably the Linux kernel)
permitting reads from <tt class="docutils literal">/dev/urandom</tt> before the system random number
generator is fully initialized, whereas most other operating systems will
implicitly block on such reads until the random number generator is ready.</p>
<p>For the lower level <tt class="docutils literal">os.urandom</tt> and <tt class="docutils literal">random.SystemRandom</tt> APIs, this PEP
proposes changing such failures in Python 3.6 from the current silent,
hard to detect, and hard to debug, errors to easily detected and debugged errors
by raising <tt class="docutils literal">BlockingIOError</tt> with a suitable error message, allowing
developers the opportunity to unambiguously specify their preferred approach
for handling the situation.</p>
<p>For the new high level <tt class="docutils literal">secrets</tt> API, it proposes to block implicitly if
needed whenever random number is generated by that module, as well as to
expose a new <tt class="docutils literal">secrets.wait_for_system_rng()</tt> function to allow code otherwise
using the low level APIs to explicitly wait for the system random number
generator to be available.</p>
<p>This change will impact any operating system that offers the <tt class="docutils literal">getrandom()</tt>
system call, regardless of whether the default behaviour of the
<tt class="docutils literal">/dev/urandom</tt> device is to return potentially predictable results when the
system random number generator is not ready (e.g. Linux, NetBSD) or to block
(e.g. FreeBSD, Solaris, Illumos). Operating systems that prevent execution of
userspace code prior to the initialization of the system random number
generator, or do not offer the <tt class="docutils literal">getrandom()</tt> syscall, will be entirely
unaffected by the proposed change (e.g. Windows, Mac OS X, OpenBSD).</p>
<p>The new exception or the blocking behaviour in the <tt class="docutils literal">secrets</tt> module would
potentially be encountered in the following situations:</p>
<ul class="simple">
<li>Python code calling these APIs during Linux system initialization</li>
<li>Python code running on improperly initialized Linux systems (e.g. embedded
hardware without adequate sources of entropy to seed the system random number
generator, or Linux VMs that aren't configured to accept entropy from the
VM host)</li>
</ul>
</div>
<div class="section" id="relationship-with-other-peps">
<h1><a class="toc-backref" href="#id24">Relationship with other PEPs</a></h1>
<p>This PEP depends on the Accepted <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a>, which adds the <tt class="docutils literal">secrets</tt> module.</p>
<p>This PEP competes with Victor Stinner's <a class="reference external" href="/dev/peps/pep-0524">PEP 524</a>, which proposes to make
<tt class="docutils literal">os.urandom</tt> itself implicitly block when the system RNG is not ready.</p>
</div>
<div class="section" id="pep-rejection">
<h1><a class="toc-backref" href="#id25">PEP Rejection</a></h1>
<p>For the reference implementation, Guido rejected this PEP in favour of the
unconditional implicit blocking proposal in <a class="reference external" href="/dev/peps/pep-0524">PEP 524</a> (which brings CPython's
behaviour on Linux into line with its behaviour on other operating systems).</p>
<p>This means any further discussion of appropriate default behaviour for
<tt class="docutils literal">os.urandom()</tt> in system Python installations in Linux distributions should
take place on the respective distro mailing lists, rather than on the upstream
CPython mailing lists.</p>
</div>
<div class="section" id="changes-independent-of-this-pep">
<h1><a class="toc-backref" href="#id26">Changes independent of this PEP</a></h1>
<p>CPython interpreter initialization and <tt class="docutils literal">random</tt> module initialization have
already been updated to gracefully fall back to alternative seeding options if
the system random number generator is not ready.</p>
<p>This PEP does not compete with the proposal in <a class="reference external" href="/dev/peps/pep-0524">PEP 524</a> to add an
<tt class="docutils literal">os.getrandom()</tt> API to expose the <tt class="docutils literal">getrandom</tt> syscall on platforms that
offer it. There is sufficient motive for adding that API in the <tt class="docutils literal">os</tt> module's
role as a thin wrapper around potentially platform dependent operating system
features that it can be added regardless of what happens to the default
behaviour of <tt class="docutils literal">os.urandom()</tt> on these systems.</p>
</div>
<div class="section" id="proposal">
<h1><a class="toc-backref" href="#id27">Proposal</a></h1>
<div class="section" id="changing-os-urandom-on-platforms-with-the-getrandom-system-call">
<h2><a class="toc-backref" href="#id28">Changing <tt class="docutils literal">os.urandom()</tt> on platforms with the getrandom() system call</a></h2>
<p>This PEP proposes that in Python 3.6+, <tt class="docutils literal">os.urandom()</tt> be updated to call
the <tt class="docutils literal">getrandom()</tt> syscall in non-blocking mode if available and raise
<tt class="docutils literal">BlockingIOError: system random number generator is not ready; see secrets.token_bytes()</tt>
if the kernel reports that the call would block.</p>
<p>This behaviour will then propagate through to the existing
<tt class="docutils literal">random.SystemRandom</tt>, which provides a relatively thin wrapper around
<tt class="docutils literal">os.urandom()</tt> that matches the <tt class="docutils literal">random.Random()</tt> API.</p>
<p>However, the new <tt class="docutils literal">secrets</tt> module introduced by <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a> will be updated to
catch the new exception and implicitly wait for the system random number
generator if the exception is ever encountered.</p>
<p>In all cases, as soon as a call to one of these security sensitive APIs
succeeds, all future calls to these APIs in that process will succeed
without blocking (once the operating system random number generator is ready
after system boot, it remains ready).</p>
<p>On Linux and NetBSD, this will replace the previous behaviour of returning
potentially predictable results read from <tt class="docutils literal">/dev/urandom</tt>.</p>
<p>On FreeBSD, Solaris, and Illumos, this will replace the previous behaviour of
implicitly blocking until the system random number generator is ready. However,
it is not clear if these operating systems actually allow userspace code (and
hence Python) to run before the system random number generator is ready.</p>
<p>Note that in all cases, if calling the underlying <tt class="docutils literal">getrandom()</tt> API reports
<tt class="docutils literal">ENOSYS</tt> rather than returning a successful response or reporting <tt class="docutils literal">EAGAIN</tt>,
CPython will continue to fall back to reading from <tt class="docutils literal">/dev/urandom</tt> directly.</p>
</div>
<div class="section" id="adding-secrets-wait-for-system-rng">
<h2><a class="toc-backref" href="#id29">Adding <tt class="docutils literal">secrets.wait_for_system_rng()</tt></a></h2>
<p>A new exception shouldn't be added without a straightforward recommendation
for how to resolve that error when encountered (however rare encountering
the new error is expected to be in practice). For security sensitive code that
actually does need to use the lower level interfaces to the system random
number generator (rather than the new <tt class="docutils literal">secrets</tt> module), and does receive
live bug reports indicating this is a real problem for the userbase of that
particular application rather than a theoretical one, this PEP's recommendation
will be to add the following snippet (directly or indirectly) to the
<tt class="docutils literal">__main__</tt> module:</p>
<pre class="literal-block">
import secrets
secrets.wait_for_system_rng()
</pre>
<p>Or, if compatibility with versions prior to Python 3.6 is needed:</p>
<pre class="literal-block">
try:
    import secrets
except ImportError:
    pass
else:
    secrets.wait_for_system_rng()
</pre>
<p>Within the <tt class="docutils literal">secrets</tt> module itself, this will then be used in
<tt class="docutils literal">token_bytes()</tt> to block implicitly if the new exception is encountered:</p>
<pre class="literal-block">
def token_bytes(nbytes=None):
    if nbytes is None:
        nbytes = DEFAULT_ENTROPY
    try:
        result = os.urandom(nbytes)
    except BlockingIOError:
        wait_for_system_rng()
        result = os.urandom(nbytes)
    return result
</pre>
<p>Other parts of the module will then be updated to use <tt class="docutils literal">token_bytes()</tt> as
their basic random number generation building block, rather than calling
<tt class="docutils literal">os.urandom()</tt> directly.</p>
<p>Application frameworks covering use cases where access to the system random
number generator is almost certain to be needed (e.g. web frameworks) may
choose to incorporate a call to <tt class="docutils literal">secrets.wait_for_system_rng()</tt> implicitly
into the commands that start the application such that existing calls to
<tt class="docutils literal">os.urandom()</tt> will be guaranteed to never raise the new exception when using
those frameworks.</p>
<p>For cases where the error is encountered for an application which cannot be
modified directly, then the following command can be used to wait for the
system random number generator to initialize before starting that application:</p>
<pre class="literal-block">
python3 -c &quot;import secrets; secrets.wait_for_system_rng()&quot;
</pre>
<p>For example, this snippet could be added to a shell script or a systemd
<tt class="docutils literal">ExecStartPre</tt> hook (and may prove useful in reliably waiting for the
system random number generator to be ready, even if the subsequent command
is not itself an application running under Python 3.6)</p>
<p>Given the changes proposed to <tt class="docutils literal">os.urandom()</tt> above, and the inclusion of
an <tt class="docutils literal">os.getrandom()</tt> API on systems that support it, the suggested
implementation of this function would be:</p>
<pre class="literal-block">
if hasattr(os, &quot;getrandom&quot;):
    # os.getrandom() always blocks waiting for the system RNG by default
    def wait_for_system_rng():
        &quot;&quot;&quot;Block waiting for system random number generator to be ready&quot;&quot;&quot;
        os.getrandom(1)
        return
else:
   # As far as we know, other platforms will never get BlockingIOError
   # below but the implementation makes pessimistic assumptions
    def wait_for_system_rng():
        &quot;&quot;&quot;Block waiting for system random number generator to be ready&quot;&quot;&quot;
        # If the system RNG is already seeded, don't wait at all
        try:
            os.urandom(1)
            return
        except BlockingIOError:
            pass
        # Avoid the below busy loop if possible
        try:
            block_on_system_rng = open(&quot;/dev/random&quot;, &quot;rb&quot;)
        except FileNotFoundError:
            pass
        else:
            with block_on_system_rng:
                block_on_system_rng.read(1)
        # Busy loop until the system RNG is ready
        while True:
            try:
                os.urandom(1)
                break
            except BlockingIOError:
                # Only check once per millisecond
                time.sleep(0.001)
</pre>
<p>On systems where it is possible to wait for the system RNG to be ready, this
function will do so without a busy loop if <tt class="docutils literal">os.getrandom()</tt> is defined,
<tt class="docutils literal">os.urandom()</tt> itself implicitly blocks, or the <tt class="docutils literal">/dev/random</tt> device is
available. If the system random number generator is ready, this call is
guaranteed to never block, even if the system's <tt class="docutils literal">/dev/random</tt> device uses
a design that permits it to block intermittently during normal system operation.</p>
</div>
<div class="section" id="limitations-on-scope">
<h2><a class="toc-backref" href="#id30">Limitations on scope</a></h2>
<p>No changes are proposed for Windows or Mac OS X systems, as neither of those
platforms provides any mechanism to run Python code before the operating
system random number generator has been initialized. Mac OS X goes so far as
to kernel panic and abort the boot process if it can't properly initialize the
random number generator (although Apple's restrictions on the supported
hardware platforms make that exceedingly unlikely in practice).</p>
<p>Similarly, no changes are proposed for other *nix systems that do not offer
the <tt class="docutils literal">getrandom()</tt> syscall. On these systems, <tt class="docutils literal">os.urandom()</tt> will continue
to block waiting for the system random number generator to be initialized.</p>
<p>While other *nix systems that offer a non-blocking API (other than
<tt class="docutils literal">getrandom()</tt>) for requesting random numbers suitable for use in security
sensitive applications could potentially receive a similar update to the one
proposed for <tt class="docutils literal">getrandom()</tt> in this PEP, such changes are out of scope for
this particular proposal.</p>
<p>Python's behaviour on older versions of affected platforms that do not offer
the new <tt class="docutils literal">getrandom()</tt> syscall will also remain unchanged.</p>
</div>
</div>
<div class="section" id="rationale">
<h1><a class="toc-backref" href="#id31">Rationale</a></h1>
<div class="section" id="ensuring-the-secrets-module-implicitly-blocks-when-needed">
<h2><a class="toc-backref" href="#id32">Ensuring the <tt class="docutils literal">secrets</tt> module implicitly blocks when needed</a></h2>
<p>This is done to help encourage the meme that arises for folks that want the
simplest possible answer to the right way to generate security sensitive random
numbers to be &quot;Use the secrets module when available or your application might
crash unexpectedly&quot;, rather than the more boilerplate heavy &quot;Always call
secrets.wait_for_system_rng() when available or your application might crash
unexpectedly&quot;.</p>
<p>It's also done due to the BDFL having a higher tolerance for APIs that might
block unexpectedly than he does for APIs that might throw an unexpected
exception <a class="footnote-reference" href="#id22" id="id1">[11]</a>.</p>
</div>
<div class="section" id="raising-blockingioerror-in-os-urandom-on-linux">
<h2><a class="toc-backref" href="#id33">Raising <tt class="docutils literal">BlockingIOError</tt> in <tt class="docutils literal">os.urandom()</tt> on Linux</a></h2>
<p>For several years now, the security community's guidance has been to use
<tt class="docutils literal">os.urandom()</tt> (or the <tt class="docutils literal">random.SystemRandom()</tt> wrapper) when implementing
security sensitive operations in Python.</p>
<p>To help improve API discoverability and make it clearer that secrecy and
simulation are not the same problem (even though they both involve
random numbers), <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a> collected several of the one line recipes based
on the lower level <tt class="docutils literal">os.urandom()</tt> API into a new <tt class="docutils literal">secrets</tt> module.</p>
<p>However, this guidance has also come with a longstanding caveat: developers
writing security sensitive software at least for Linux, and potentially for
some other *BSD systems, may need to wait until the operating system's
random number generator is ready before relying on it for security sensitive
operations. This generally only occurs if <tt class="docutils literal">os.urandom()</tt> is read very
early in the system initialization process, or on systems with few sources of
available entropy (e.g. some kinds of virtualized or embedded systems), but
unfortunately the exact conditions that trigger this are difficult to predict,
and when it occurs then there is no direct way for userspace to tell it has
happened without querying operating system specific interfaces.</p>
<p>On *BSD systems (if the particular *BSD variant allows the problem to occur
at all) and potentially also Solaris and Illumos, encountering this situation
means <tt class="docutils literal">os.urandom()</tt> will either block waiting for the system random number
generator to be ready (the associated symptom would be for the affected script
to pause unexpectedly on the first call to <tt class="docutils literal">os.urandom()</tt>) or else will
behave the same way as it does on Linux.</p>
<p>On Linux, in Python versions up to and including Python 3.4, and in
Python 3.5 maintenance versions following Python 3.5.2, there's no clear
indicator to developers that their software may not be working as expected
when run early in the Linux boot process, or on hardware without good
sources of entropy to seed the operating system's random number generator: due
to the behaviour of the underlying <tt class="docutils literal">/dev/urandom</tt> device, <tt class="docutils literal">os.urandom()</tt>
on Linux returns a result either way, and it takes extensive statistical
analysis to show that a security vulnerability exists.</p>
<p>By contrast, if <tt class="docutils literal">BlockingIOError</tt> is raised in those situations, then
developers using Python 3.6+ can easily choose their desired behaviour:</p>
<ol class="arabic simple">
<li>Wait for the system RNG at or before application startup (security sensitive)</li>
<li>Switch to using the random module (non-security sensitive)</li>
</ol>
</div>
<div class="section" id="making-secrets-wait-for-system-rng-public">
<h2><a class="toc-backref" href="#id34">Making <tt class="docutils literal">secrets.wait_for_system_rng()</tt> public</a></h2>
<p>Earlier versions of this PEP proposed a number of recipes for wrapping
<tt class="docutils literal">os.urandom()</tt> to make it suitable for use in security sensitive use cases.</p>
<p>Discussion of the proposal on the security-sig mailing list prompted the
realization <a class="footnote-reference" href="#id20" id="id2">[9]</a> that the core assumption driving the API design in this PEP
was that choosing between letting the exception cause the application to fail,
blocking waiting for the system RNG to be ready and switching to using the
<tt class="docutils literal">random</tt> module instead of <tt class="docutils literal">os.urandom</tt> is an application and use-case
specific decision that should take into account application and use-case
specific details.</p>
<p>There is no way for the interpreter runtime or support libraries to determine
whether a particular use case is security sensitive or not, and while it's
straightforward for application developer to decide how to handle an exception
thrown by a particular API, they can't readily workaround an API blocking when
they expected it to be non-blocking.</p>
<p>Accordingly, the PEP was updated to add <tt class="docutils literal">secrets.wait_for_system_rng()</tt> as
an API for applications, scripts and frameworks to use to indicate that they
wanted to ensure the system RNG was available before continuing, while library
developers could continue to call <tt class="docutils literal">os.urandom()</tt> without worrying that it
might unexpectedly start blocking waiting for the system RNG to be available.</p>
</div>
</div>
<div class="section" id="backwards-compatibility-impact-assessment">
<h1><a class="toc-backref" href="#id35">Backwards Compatibility Impact Assessment</a></h1>
<p>Similar to <a class="reference external" href="/dev/peps/pep-0476">PEP 476</a>, this is a proposal to turn a previously silent security
failure into a noisy exception that requires the application developer to
make an explicit decision regarding the behaviour they desire.</p>
<p>As no changes are proposed for operating systems that don't provide the
<tt class="docutils literal">getrandom()</tt> syscall, <tt class="docutils literal">os.urandom()</tt> retains its existing behaviour as
a nominally blocking API that is non-blocking in practice due to the difficulty
of scheduling Python code to run before the operating system random number
generator is ready. We believe it may be possible to encounter problems akin to
those described in this PEP on at least some *BSD variants, but nobody has
explicitly demonstrated that. On Mac OS X and Windows, it appears to be
straight up impossible to even try to run a Python interpreter that early in
the boot process.</p>
<p>On Linux and other platforms with similar <tt class="docutils literal">/dev/urandom</tt> behaviour,
<tt class="docutils literal">os.urandom()</tt> retains its status as a guaranteed non-blocking API.
However, the means of achieving that status changes in the specific case of
the operating system random number generator not being ready for use in security
sensitive operations: historically it would return potentially predictable
random data, with this PEP it would change to raise <tt class="docutils literal">BlockingIOError</tt>.</p>
<p>Developers of affected applications would then be required to make one of the
following changes to gain forward compatibility with Python 3.6, based on the
kind of application they're developing.</p>
<div class="section" id="unaffected-applications">
<h2><a class="toc-backref" href="#id36">Unaffected Applications</a></h2>
<p>The following kinds of applications would be entirely unaffected by the change,
regardless of whether or not they perform security sensitive operations:</p>
<ul class="simple">
<li>applications that don't support Linux</li>
<li>applications that are only run on desktops or conventional servers</li>
<li>applications that are only run after the system RNG is ready (including
those where an application framework calls <tt class="docutils literal">secrets.wait_for_system_rng()</tt>
on their behalf)</li>
</ul>
<p>Applications in this category simply won't encounter the new exception, so it
will be reasonable for developers to wait and see if they receive
Python 3.6 compatibility bugs related to the new runtime behaviour, rather than
attempting to pre-emptively determine whether or not they're affected.</p>
</div>
<div class="section" id="affected-security-sensitive-applications">
<h2><a class="toc-backref" href="#id37">Affected security sensitive applications</a></h2>
<p>Security sensitive applications would need to either change their system
configuration so the application is only started after the operating system
random number generator is ready for security sensitive operations, change the
application startup code to invoke <tt class="docutils literal">secrets.wait_for_system_rng()</tt>, or
else switch to using the new <tt class="docutils literal">secrets.token_bytes()</tt> API.</p>
<p>As an example for components started via a systemd unit file, the following
snippet would delay activation until the system RNG was ready:</p>
<blockquote>
ExecStartPre=python3 -c &quot;import secrets; secrets.wait_for_system_rng()&quot;</blockquote>
<p>Alternatively, the following snippet will use <tt class="docutils literal">secrets.token_bytes()</tt> if
available, and fall back to <tt class="docutils literal">os.urandom()</tt> otherwise:</p>
<blockquote>
<dl class="docutils">
<dt>try:</dt>
<dd>import secrets.token_bytes as _get_random_bytes</dd>
<dt>except ImportError:</dt>
<dd>import os.urandom as _get_random_bytes</dd>
</dl>
</blockquote>
</div>
<div class="section" id="affected-non-security-sensitive-applications">
<h2><a class="toc-backref" href="#id38">Affected non-security sensitive applications</a></h2>
<p>Non-security sensitive applications should be updated to use the <tt class="docutils literal">random</tt>
module rather than <tt class="docutils literal">os.urandom</tt>:</p>
<pre class="literal-block">
def pseudorandom_bytes(num_bytes):
    return random.getrandbits(num_bytes*8).to_bytes(num_bytes, &quot;little&quot;)
</pre>
<p>Depending on the details of the application, the random module may offer
other APIs that can be used directly, rather than needing to emulate the
raw byte sequence produced by the <tt class="docutils literal">os.urandom()</tt> API.</p>
</div>
</div>
<div class="section" id="additional-background">
<h1><a class="toc-backref" href="#id39">Additional Background</a></h1>
<div class="section" id="why-propose-this-now">
<h2><a class="toc-backref" href="#id40">Why propose this now?</a></h2>
<p>The main reason is because the Python 3.5.0 release switched to using the new
Linux <tt class="docutils literal">getrandom()</tt> syscall when available in order to avoid consuming a
file descriptor <a class="footnote-reference" href="#id12" id="id3">[1]</a>, and this had the side effect of making the following
operations block waiting for the system random number generator to be ready:</p>
<ul class="simple">
<li><tt class="docutils literal">os.urandom</tt> (and APIs that depend on it)</li>
<li>importing the <tt class="docutils literal">random</tt> module</li>
<li>initializing the randomized hash algorithm used by some builtin types</li>
</ul>
<p>While the first of those behaviours is arguably desirable (and consistent with
the existing behaviour of <tt class="docutils literal">os.urandom</tt> on other operating systems), the
latter two behaviours are unnecessary and undesirable, and the last one is now
known to cause a system level deadlock when attempting to run Python scripts
during the Linux init process with Python 3.5.0 or 3.5.1 <a class="footnote-reference" href="#id13" id="id4">[2]</a>, while the second
one can cause problems when using virtual machines without robust entropy
sources configured <a class="footnote-reference" href="#id14" id="id5">[3]</a>.</p>
<p>Since decoupling these behaviours in CPython will involve a number of
implementation changes more appropriate for a feature release than a maintenance
release, the relatively simple resolution applied in Python 3.5.2 was to revert
all three of them to a behaviour similar to that of previous Python versions:
if the new Linux syscall indicates it will block, then Python 3.5.2 will
implicitly fall back on reading <tt class="docutils literal">/dev/urandom</tt> directly <a class="footnote-reference" href="#id15" id="id6">[4]</a>.</p>
<p>However, this bug report <em>also</em> resulted in a range of proposals to add <em>new</em>
APIs like <tt class="docutils literal">os.getrandom()</tt> <a class="footnote-reference" href="#id16" id="id7">[5]</a>, <tt class="docutils literal">os.urandom_block()</tt> <a class="footnote-reference" href="#id17" id="id8">[6]</a>,
<tt class="docutils literal">os.pseudorandom()</tt> and <tt class="docutils literal">os.cryptorandom()</tt> <a class="footnote-reference" href="#id18" id="id9">[7]</a>, or adding new optional
parameters to <tt class="docutils literal">os.urandom()</tt> itself <a class="footnote-reference" href="#id19" id="id10">[8]</a>, and then attempting to educate
users on when they should call those APIs instead of just using a plain
<tt class="docutils literal">os.urandom()</tt> call.</p>
<p>These proposals arguably represent overreactions, as the question of reliably
obtaining random numbers suitable for security sensitive work on Linux is a
relatively obscure problem of interest mainly to operating system developers
and embedded systems programmers, that may not justify expanding the
Python standard library's cross-platform APIs with new Linux-specific concerns.
This is especially so with the <tt class="docutils literal">secrets</tt> module already being added as the
&quot;use this and don't worry about the low level details&quot; option for developers
writing security sensitive software that for some reason can't rely on even
higher level domain specific APIs (like web frameworks) and also don't need to
worry about Python versions prior to Python 3.6.</p>
<p>That said, it's also the case that low cost ARM devices are becoming
increasingly prevalent, with a lot of them running Linux, and a lot of folks
writing Python applications that run on those devices. That creates an
opportunity to take an obscure security problem that currently requires a lot
of knowledge about Linux boot processes and provably unpredictable random
number generation to diagnose and resolve, and instead turn it into a
relatively mundane and easy-to-find-in-an-internet-search runtime exception.</p>
</div>
<div class="section" id="the-cross-platform-behaviour-of-os-urandom">
<h2><a class="toc-backref" href="#id41">The cross-platform behaviour of <tt class="docutils literal">os.urandom()</tt></a></h2>
<p>On operating systems other than Linux and NetBSD, <tt class="docutils literal">os.urandom()</tt> may already
block waiting for the operating system's random number generator to be ready.
This will happen at most once in the lifetime of the process, and the call is
subsequently guaranteed to be non-blocking.</p>
<p>Linux and NetBSD are outliers in that, even when the operating system's random
number generator doesn't consider itself ready for use in security sensitive
operations, reading from the <tt class="docutils literal">/dev/urandom</tt> device will return random values
based on the entropy it has available.</p>
<p>This behaviour is potentially problematic, so Linux 3.17 added a new
<tt class="docutils literal">getrandom()</tt> syscall that (amongst other benefits) allows callers to
either block waiting for the random number generator to be ready, or
else request an error return if the random number generator is not ready.
Notably, the new API does <em>not</em> support the old behaviour of returning
data that is not suitable for security sensitive use cases.</p>
<p>Versions of Python prior up to and including Python 3.4 access the
Linux <tt class="docutils literal">/dev/urandom</tt> device directly.</p>
<p>Python 3.5.0 and 3.5.1 (when build on a system that offered the new syscall)
called <tt class="docutils literal">getrandom()</tt> in blocking mode in order to avoid the use of a file
descriptor to access <tt class="docutils literal">/dev/urandom</tt>. While there were no specific problems
reported due to <tt class="docutils literal">os.urandom()</tt> blocking in user code, there <em>were</em> problems
due to CPython implicitly invoking the blocking behaviour during interpreter
startup and when importing the <tt class="docutils literal">random</tt> module.</p>
<p>Rather than trying to decouple SipHash initialization from the
<tt class="docutils literal">os.urandom()</tt> implementation, Python 3.5.2 switched to calling
<tt class="docutils literal">getrandom()</tt> in non-blocking mode, and falling back to reading from
<tt class="docutils literal">/dev/urandom</tt> if the syscall indicates it will block.</p>
<p>As a result of the above, <tt class="docutils literal">os.urandom()</tt> in all Python versions up to and
including Python 3.5 propagate the behaviour of the underling <tt class="docutils literal">/dev/urandom</tt>
device to Python code.</p>
</div>
<div class="section" id="problems-with-the-behaviour-of-dev-urandom-on-linux">
<h2><a class="toc-backref" href="#id42">Problems with the behaviour of <tt class="docutils literal">/dev/urandom</tt> on Linux</a></h2>
<p>The Python <tt class="docutils literal">os</tt> module has largely co-evolved with Linux APIs, so having
<tt class="docutils literal">os</tt> module functions closely follow the behaviour of their Linux operating
system level counterparts when running on Linux is typically considered to be
a desirable feature.</p>
<p>However, <tt class="docutils literal">/dev/urandom</tt> represents a case where the current behaviour is
acknowledged to be problematic, but fixing it unilaterally at the kernel level
has been shown to prevent some Linux distributions from booting (at least in
part due to components like Python currently using it for
non-security-sensitive purposes early in the system initialization process).</p>
<p>As an analogy, consider the following two functions:</p>
<pre class="literal-block">
def generate_example_password():
    &quot;&quot;&quot;Generates passwords solely for use in code examples&quot;&quot;&quot;
    return generate_unpredictable_password()

def generate_actual_password():
    &quot;&quot;&quot;Generates actual passwords for use in real applications&quot;&quot;&quot;
    return generate_unpredictable_password()
</pre>
<p>If you think of an operating system's random number generator as a method for
generating unpredictable, secret passwords, then you can think of Linux's
<tt class="docutils literal">/dev/urandom</tt> as being implemented like:</p>
<pre class="literal-block">
# Oversimplified artist's conception of the kernel code
# implementing /dev/urandom
def generate_unpredictable_password():
    if system_rng_is_ready:
        return use_system_rng_to_generate_password()
    else:
        # we can't make an unpredictable password; silently return a
        # potentially predictable one instead:
        return &quot;p4ssw0rd&quot;
</pre>
<p>In this scenario, the author of <tt class="docutils literal">generate_example_password</tt> is fine - even if
<tt class="docutils literal">&quot;p4ssw0rd&quot;</tt> shows up a bit more often than they expect, it's only used in
examples anyway. However, the author of <tt class="docutils literal">generate_actual_password</tt> has a
problem - how do they prove that their calls to
<tt class="docutils literal">generate_unpredictable_password</tt> never follow the path that returns a
predictable answer?</p>
<p>In real life it's slightly more complicated than this, because there
might be some level of system entropy available -- so the fallback might
be more like <tt class="docutils literal">return <span class="pre">random.choice([&quot;p4ssword&quot;,</span> &quot;passw0rd&quot;,
<span class="pre">&quot;p4ssw0rd&quot;])</span></tt> or something even more variable and hence only statistically
predictable with better odds than the author of <tt class="docutils literal">generate_actual_password</tt>
was expecting. This doesn't really make things more provably secure, though;
mostly it just means that if you try to catch the problem in the obvious way --
<tt class="docutils literal">if returned_password == &quot;p4ssw0rd&quot;: raise UhOh</tt> -- then it doesn't work,
because <tt class="docutils literal">returned_password</tt> might instead be <tt class="docutils literal">p4ssword</tt> or even
<tt class="docutils literal">pa55word</tt>, or just an arbitrary 64 bit sequence selected from fewer than
2**64 possibilities. So this rough sketch does give the right general idea of
the consequences of the &quot;more predictable than expected&quot; fallback behaviour,
even though it's thoroughly unfair to the Linux kernel team's efforts to
mitigate the practical consequences of this problem without resorting to
breaking backwards compatibility.</p>
<p>This design is generally agreed to be a bad idea. As far as we can
tell, there are no use cases whatsoever in which this is the behavior
you actually want. It has led to the use of insecure <tt class="docutils literal">ssh</tt> keys on
real systems, and many *nix-like systems (including at least Mac OS
X, OpenBSD, and FreeBSD) have modified their <tt class="docutils literal">/dev/urandom</tt>
implementations so that they never return predictable outputs, either
by making reads block in this case, or by simply refusing to run any
userspace programs until the system RNG has been
initialized. Unfortunately, Linux has so far been unable to follow
suit, because it's been empirically determined that enabling the
blocking behavior causes some currently extant distributions to
fail to boot.</p>
<p>Instead, the new <tt class="docutils literal">getrandom()</tt> syscall was introduced, making
it <em>possible</em> for userspace applications to access the system random number
generator safely, without introducing hard to debug deadlock problems into
the system initialization processes of existing Linux distros.</p>
</div>
<div class="section" id="consequences-of-getrandom-availability-for-python">
<h2><a class="toc-backref" href="#id43">Consequences of <tt class="docutils literal">getrandom()</tt> availability for Python</a></h2>
<p>Prior to the introduction of the <tt class="docutils literal">getrandom()</tt> syscall, it simply wasn't
feasible to access the Linux system random number generator in a provably
safe way, so we were forced to settle for reading from <tt class="docutils literal">/dev/urandom</tt> as the
best available option. However, with <tt class="docutils literal">getrandom()</tt> insisting on raising an
error or blocking rather than returning predictable data, as well as having
other advantages, it is now the recommended method for accessing the kernel
RNG on Linux, with reading <tt class="docutils literal">/dev/urandom</tt> directly relegated to &quot;legacy&quot;
status. This moves Linux into the same category as other operating systems
like Windows, which doesn't provide a <tt class="docutils literal">/dev/urandom</tt> device at all: the
best available option for implementing <tt class="docutils literal">os.urandom()</tt> is no longer simply
reading bytes from the <tt class="docutils literal">/dev/urandom</tt> device.</p>
<p>This means that what used to be somebody else's problem (the Linux kernel
development team's) is now Python's problem -- given a way to detect that the
system RNG is not initialized, we have to choose how to handle this
situation whenever we try to use the system RNG.</p>
<p>It could simply block, as was somewhat inadvertently implemented in 3.5.0,
and as is proposed in Victor Stinner's competing PEP:</p>
<pre class="literal-block">
# artist's impression of the CPython 3.5.0-3.5.1 behavior
def generate_unpredictable_bytes_or_block(num_bytes):
    while not system_rng_is_ready:
        wait
    return unpredictable_bytes(num_bytes)
</pre>
<p>Or it could raise an error, as this PEP proposes (in <em>some</em> cases):</p>
<pre class="literal-block">
# artist's impression of the behavior proposed in this PEP
def generate_unpredictable_bytes_or_raise(num_bytes):
    if system_rng_is_ready:
        return unpredictable_bytes(num_bytes)
    else:
        raise BlockingIOError
</pre>
<p>Or it could explicitly emulate the <tt class="docutils literal">/dev/urandom</tt> fallback behavior,
as was implemented in 3.5.2rc1 and is expected to remain for the rest
of the 3.5.x cycle:</p>
<pre class="literal-block">
# artist's impression of the CPython 3.5.2rc1+ behavior
def generate_unpredictable_bytes_or_maybe_not(num_bytes):
    if system_rng_is_ready:
        return unpredictable_bytes(num_bytes)
    else:
        return (b&quot;p4ssw0rd&quot; * (num_bytes // 8 + 1))[:num_bytes]
</pre>
<p>(And the same caveats apply to this sketch as applied to the
<tt class="docutils literal">generate_unpredictable_password</tt> sketch of <tt class="docutils literal">/dev/urandom</tt> above.)</p>
<p>There are five places where CPython and the standard library attempt to use the
operating system's random number generator, and thus five places where this
decision has to be made:</p>
<ul class="simple">
<li>initializing the SipHash used to protect <tt class="docutils literal">str.__hash__</tt> and
friends against DoS attacks (called unconditionally at startup)</li>
<li>initializing the <tt class="docutils literal">random</tt> module (called when <tt class="docutils literal">random</tt> is
imported)</li>
<li>servicing user calls to the <tt class="docutils literal">os.urandom</tt> public API</li>
<li>the higher level <tt class="docutils literal">random.SystemRandom</tt> public API</li>
<li>the new <tt class="docutils literal">secrets</tt> module public API added by <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a></li>
</ul>
<p>Previously, these five places all used the same underlying code, and
thus made this decision in the same way.</p>
<p>This whole problem was first noticed because 3.5.0 switched that
underlying code to the <tt class="docutils literal">generate_unpredictable_bytes_or_block</tt> behavior,
and it turns out that there are some rare cases where Linux boot
scripts attempted to run a Python program as part of system initialization, the
Python startup sequence blocked while trying to initialize SipHash,
and then this triggered a deadlock because the system stopped doing
anything -- including gathering new entropy -- until the Python script
was forcibly terminated by an external timer. This is particularly unfortunate
since the scripts in question never processed untrusted input, so there was no
need for SipHash to be initialized with provably unpredictable random data in
the first place. This motivated the change in 3.5.2rc1 to emulate the old
<tt class="docutils literal">/dev/urandom</tt> behavior in all cases (by calling <tt class="docutils literal">getrandom()</tt> in
non-blocking mode, and then falling back to reading <tt class="docutils literal">/dev/urandom</tt>
if the syscall indicates that the <tt class="docutils literal">/dev/urandom</tt> pool is not yet
fully initialized.)</p>
<p>We don't know whether such problems may also exist in the Fedora/RHEL/CentOS
ecosystem, as the build systems for those distributions use chroots on servers
running an older operating system kernel that doesn't offer the <tt class="docutils literal">getrandom()</tt>
syscall, which means CPython's current build configuration compiles out the
runtime check for that syscall <a class="footnote-reference" href="#id21" id="id11">[10]</a>.</p>
<p>A similar problem was found due to the <tt class="docutils literal">random</tt> module calling
<tt class="docutils literal">os.urandom</tt> as a side-effect of import in order to seed the default
global <tt class="docutils literal">random.Random()</tt> instance.</p>
<p>We have not received any specific complaints regarding direct calls to
<tt class="docutils literal">os.urandom()</tt> or <tt class="docutils literal">random.SystemRandom()</tt> blocking with 3.5.0 or 3.5.1 -
only problem reports due to the implicit blocking on interpreter startup and
as a side-effect of importing the random module.</p>
<p>Independently of this PEP, the first two cases have already been updated to
never block, regardless of the behaviour of <tt class="docutils literal">os.urandom()</tt>.</p>
<p>Where <a class="reference external" href="/dev/peps/pep-0524">PEP 524</a> proposes to make all 3 of the latter cases block implicitly,
this PEP proposes that approach only for the last case (the <tt class="docutils literal">secrets</tt>)
module, with <tt class="docutils literal">os.urandom()</tt> and <tt class="docutils literal">random.SystemRandom()</tt> instead raising
an exception when they detect that the underlying operating system call
would block.</p>
</div>
</div>
<div class="section" id="references">
<h1><a class="toc-backref" href="#id44">References</a></h1>
<table class="docutils footnote" frame="void" id="id12" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id3">[1]</a></td><td>os.urandom() should use Linux 3.17 getrandom() syscall
(<a class="reference external" href="http://bugs.python.org/issue22181">http://bugs.python.org/issue22181</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id13" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id4">[2]</a></td><td>Python 3.5 running on Linux kernel 3.17+ can block at startup or on
importing the random module on getrandom()
(<a class="reference external" href="http://bugs.python.org/issue26839">http://bugs.python.org/issue26839</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id14" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id5">[3]</a></td><td>&quot;import random&quot; blocks on entropy collection on Linux with low entropy
(<a class="reference external" href="http://bugs.python.org/issue25420">http://bugs.python.org/issue25420</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id15" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id6">[4]</a></td><td>os.urandom() doesn't block on Linux anymore
(<a class="reference external" href="https://hg.python.org/cpython/rev/9de508dc4837">https://hg.python.org/cpython/rev/9de508dc4837</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id16" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id7">[5]</a></td><td>Proposal to add os.getrandom()
(<a class="reference external" href="http://bugs.python.org/issue26839#msg267803">http://bugs.python.org/issue26839#msg267803</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id17" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id8">[6]</a></td><td>Add os.urandom_block()
(<a class="reference external" href="http://bugs.python.org/issue27250">http://bugs.python.org/issue27250</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id18" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id9">[7]</a></td><td>Add random.cryptorandom() and random.pseudorandom, deprecate os.urandom()
(<a class="reference external" href="http://bugs.python.org/issue27279">http://bugs.python.org/issue27279</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id19" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id10">[8]</a></td><td>Always use getrandom() in os.random() on Linux and add
block=False parameter to os.urandom()
(<a class="reference external" href="http://bugs.python.org/issue27266">http://bugs.python.org/issue27266</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id20" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id2">[9]</a></td><td>Application level vs library level design decisions
(<a class="reference external" href="https://mail.python.org/pipermail/security-sig/2016-June/000057.html">https://mail.python.org/pipermail/security-sig/2016-June/000057.html</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id21" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id11">[10]</a></td><td>Does the HAVE_GETRANDOM_SYSCALL config setting make sense?
(<a class="reference external" href="https://mail.python.org/pipermail/security-sig/2016-June/000060.html">https://mail.python.org/pipermail/security-sig/2016-June/000060.html</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id22" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[11]</a></td><td>Take a decision for os.urandom() in Python 3.6
(<a class="reference external" href="https://mail.python.org/pipermail/security-sig/2016-August/000084.htm">https://mail.python.org/pipermail/security-sig/2016-August/000084.htm</a>)</td></tr>
</tbody>
</table>
<p>For additional background details beyond those captured in this PEP and Victor's
competing PEP, also see Victor's prior collection of relevant information and
links at <a class="reference external" href="https://haypo-notes.readthedocs.io/summary_python_random_issue.html">https://haypo-notes.readthedocs.io/summary_python_random_issue.html</a></p>
</div>
<div class="section" id="copyright">
<h1><a class="toc-backref" href="#id45">Copyright</a></h1>
<p>This document has been placed into the public domain.</p>
<!-- Local Variables:
mode: indented-text
indent-tabs-mode: nil
sentence-end-double-space: t
fill-column: 70
coding: utf-8 -->
</div>

