<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
PEP, see http://www.python.org/dev/peps/pep-0001 for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->
<table class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">PEP:</th><td class="field-body">409</td>
</tr>
<tr class="field"><th class="field-name">Title:</th><td class="field-body">Suppressing exception context</td>
</tr>
<tr class="field"><th class="field-name">Version:</th><td class="field-body">$Revision$</td>
</tr>
<tr class="field"><th class="field-name">Last-Modified:</th><td class="field-body"><a class="reference external" href="https://hg.python.org/peps/file/tip/pep-0409.txt">$Date$</a></td>
</tr>
<tr class="field"><th class="field-name">Author:</th><td class="field-body">Ethan Furman &lt;ethan&#32;&#97;t&#32;stoneleaf.us&gt;</td>
</tr>
<tr class="field"><th class="field-name">Status:</th><td class="field-body">Final</td>
</tr>
<tr class="field"><th class="field-name">Type:</th><td class="field-body">Standards Track</td>
</tr>
<tr class="field"><th class="field-name">Content-Type:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0012">text/x-rst</a></td>
</tr>
<tr class="field"><th class="field-name">Created:</th><td class="field-body">26-Jan-2012</td>
</tr>
<tr class="field"><th class="field-name">Post-History:</th><td class="field-body">30-Aug-2002, 01-Feb-2012, 03-Feb-2012</td>
</tr>
<tr class="field"><th class="field-name">Superseded-By:</th><td class="field-body">415</td>
</tr>
<tr class="field"><th class="field-name">Resolution:</th><td class="field-body"><a class="reference external" href="https://mail.python.org/pipermail/python-dev/2012-February/116136.html">https://mail.python.org/pipermail/python-dev/2012-February/116136.html</a></td>
</tr>
</tbody>
</table>
<hr />
<div class="contents topic" id="contents">
<p class="topic-title first">Contents</p>
<ul class="simple">
<li><a class="reference internal" href="#abstract" id="id7">Abstract</a></li>
<li><a class="reference internal" href="#rationale" id="id8">Rationale</a></li>
<li><a class="reference internal" href="#alternatives" id="id9">Alternatives</a></li>
<li><a class="reference internal" href="#proposal" id="id10">Proposal</a></li>
<li><a class="reference internal" href="#implementation-discussion" id="id11">Implementation Discussion</a></li>
<li><a class="reference internal" href="#language-details" id="id12">Language Details</a></li>
<li><a class="reference internal" href="#patches" id="id13">Patches</a></li>
<li><a class="reference internal" href="#references" id="id14">References</a></li>
<li><a class="reference internal" href="#copyright" id="id15">Copyright</a></li>
</ul>
</div>
<div class="section" id="abstract">
<h1><a class="toc-backref" href="#id7">Abstract</a></h1>
<p>One of the open issues from <a class="reference external" href="/dev/peps/pep-3134">PEP 3134</a> is suppressing context:  currently
there is no way to do it.  This PEP proposes one.</p>
</div>
<div class="section" id="rationale">
<h1><a class="toc-backref" href="#id8">Rationale</a></h1>
<p>There are two basic ways to generate exceptions:</p>
<ol class="arabic simple">
<li>Python does it (buggy code, missing resources, ending loops, etc.)</li>
<li>manually (with a raise statement)</li>
</ol>
<p>When writing libraries, or even just custom classes, it can become
necessary to raise exceptions; moreover it can be useful, even
necessary, to change from one exception to another.  To take an example
from my dbf module:</p>
<pre class="literal-block">
try:
    value = int(value)
except Exception:
    raise DbfError(...)
</pre>
<p>Whatever the original exception was (<tt class="docutils literal">ValueError</tt>, <tt class="docutils literal">TypeError</tt>, or
something else) is irrelevant.  The exception from this point on is a
<tt class="docutils literal">DbfError</tt>, and the original exception is of no value.  However, if
this exception is printed, we would currently see both.</p>
</div>
<div class="section" id="alternatives">
<h1><a class="toc-backref" href="#id9">Alternatives</a></h1>
<p>Several possibilities have been put forth:</p>
<ul>
<li><p class="first"><tt class="docutils literal">raise as NewException()</tt></p>
<p>Reuses the <tt class="docutils literal">as</tt> keyword; can be confusing since we are not really
reraising the originating exception</p>
</li>
<li><p class="first"><tt class="docutils literal">raise NewException() from None</tt></p>
<p>Follows existing syntax of explicitly declaring the originating
exception</p>
</li>
<li><p class="first"><tt class="docutils literal">exc = <span class="pre">NewException();</span> exc.__context__ = None; raise exc</tt></p>
<p>Very verbose way of the previous method</p>
</li>
<li><p class="first"><tt class="docutils literal">raise <span class="pre">NewException.no_context(...)</span></tt></p>
<p>Make context suppression a class method.</p>
</li>
</ul>
<p>All of the above options will require changes to the core.</p>
</div>
<div class="section" id="proposal">
<h1><a class="toc-backref" href="#id10">Proposal</a></h1>
<p>I propose going with the second option:</p>
<pre class="literal-block">
raise NewException from None
</pre>
<p>It has the advantage of using the existing pattern of explicitly setting
the cause:</p>
<pre class="literal-block">
raise KeyError() from NameError()
</pre>
<p>but because the cause is <tt class="docutils literal">None</tt> the previous context is not displayed
by the default exception printing routines.</p>
</div>
<div class="section" id="implementation-discussion">
<h1><a class="toc-backref" href="#id11">Implementation Discussion</a></h1>
<p>Note: after acceptance of this PEP, a cleaner implementation mechanism
was proposed and accepted in <a class="reference external" href="/dev/peps/pep-0415">PEP 415</a>. Refer to that PEP for more
details on the implementation actually used in Python 3.3.</p>
<p>Currently, <tt class="docutils literal">None</tt> is the default for both <tt class="docutils literal">__context__</tt> and <tt class="docutils literal">__cause__</tt>.
In order to support <tt class="docutils literal">raise ... from None</tt> (which would set <tt class="docutils literal">__cause__</tt> to
<tt class="docutils literal">None</tt>) we need a different default value for <tt class="docutils literal">__cause__</tt>.  Several ideas
were put forth on how to implement this at the language level:</p>
<ul>
<li><p class="first">Overwrite the previous exception information (side-stepping the issue and
leaving <tt class="docutils literal">__cause__</tt> at <tt class="docutils literal">None</tt>).</p>
<p>Rejected as this can seriously hinder debugging due to
<a class="reference external" href="http://bugs.python.org/msg152294">poor error messages</a> <a class="footnote-reference" href="#id1" id="id2">[1]</a>.</p>
</li>
<li><p class="first">Use one of the boolean values in <tt class="docutils literal">__cause__</tt>:  <tt class="docutils literal">False</tt> would be the
default value, and would be replaced when <tt class="docutils literal">from ...</tt> was used with the
explicitly chained exception or <tt class="docutils literal">None</tt>.</p>
<p>Rejected as this encourages the use of two different objects types for
<tt class="docutils literal">__cause__</tt> with one of them (boolean) not allowed to have the full range
of possible values (<tt class="docutils literal">True</tt> would never be used).</p>
</li>
<li><p class="first">Create a special exception class, <tt class="docutils literal">__NoException__</tt>.</p>
<p>Rejected as possibly confusing, possibly being mistakenly raised by users,
and not being a truly unique value as <tt class="docutils literal">None</tt>, <tt class="docutils literal">True</tt>, and <tt class="docutils literal">False</tt> are.</p>
</li>
<li><p class="first">Use <tt class="docutils literal">Ellipsis</tt> as the default value (the <tt class="docutils literal">...</tt> singleton).</p>
<p>Accepted.</p>
<p>Ellipses are commonly used in English as place holders when words are
omitted.  This works in our favor here as a signal that <tt class="docutils literal">__cause__</tt> is
omitted, so look in <tt class="docutils literal">__context__</tt> for more details.</p>
<p>Ellipsis is not an exception, so cannot be raised.</p>
<p>There is only one Ellipsis, so no unused values.</p>
<p>Error information is not thrown away, so custom code can trace the entire
exception chain even if the default code does not.</p>
</li>
</ul>
</div>
<div class="section" id="language-details">
<h1><a class="toc-backref" href="#id12">Language Details</a></h1>
<p>To support <tt class="docutils literal">raise Exception from None</tt>, <tt class="docutils literal">__context__</tt> will stay as it is,
but <tt class="docutils literal">__cause__</tt> will start out as <tt class="docutils literal">Ellipsis</tt> and will change to <tt class="docutils literal">None</tt>
when the <tt class="docutils literal">raise Exception from None</tt> method is used.</p>
<table border="1" class="docutils">
<colgroup>
<col width="44%" />
<col width="18%" />
<col width="39%" />
</colgroup>
<thead valign="bottom">
<tr><th class="head">form</th>
<th class="head">__context__</th>
<th class="head">__cause__</th>
</tr>
</thead>
<tbody valign="top">
<tr><td>raise</td>
<td><tt class="docutils literal">None</tt></td>
<td><tt class="docutils literal">Ellipsis</tt></td>
</tr>
<tr><td>reraise</td>
<td>previous exception</td>
<td><tt class="docutils literal">Ellipsis</tt></td>
</tr>
<tr><td>reraise from <tt class="docutils literal">None</tt> | <tt class="docutils literal">ChainedException</tt></td>
<td>previous exception</td>
<td><tt class="docutils literal">None</tt> | explicitly chained exception</td>
</tr>
</tbody>
</table>
<p>The default exception printing routine will then:</p>
<ul class="simple">
<li>If <tt class="docutils literal">__cause__</tt> is <tt class="docutils literal">Ellipsis</tt> the <tt class="docutils literal">__context__</tt> (if any) will be
printed.</li>
<li>If <tt class="docutils literal">__cause__</tt> is <tt class="docutils literal">None</tt> the <tt class="docutils literal">__context__</tt> will not be printed.</li>
<li>if <tt class="docutils literal">__cause__</tt> is anything else, <tt class="docutils literal">__cause__</tt> will be printed.</li>
</ul>
<p>In both of the latter cases the exception chain will stop being followed.</p>
<p>Because the default value for <tt class="docutils literal">__cause__</tt> is now <tt class="docutils literal">Ellipsis</tt> and <tt class="docutils literal">raise
Exception from Cause</tt> is simply syntactic sugar for:</p>
<pre class="literal-block">
_exc = NewException()
_exc.__cause__ = Cause()
raise _exc
</pre>
<p><tt class="docutils literal">Ellipsis</tt>, as well as <tt class="docutils literal">None</tt>, is now allowed as a cause:</p>
<pre class="literal-block">
raise Exception from Ellipsis
</pre>
</div>
<div class="section" id="patches">
<h1><a class="toc-backref" href="#id13">Patches</a></h1>
<p>There is a patch for CPython implementing this attached to <a class="reference external" href="http://bugs.python.org/issue6210">Issue 6210</a> <a class="footnote-reference" href="#id3" id="id4">[2]</a>.</p>
</div>
<div class="section" id="references">
<h1><a class="toc-backref" href="#id14">References</a></h1>
<p>Discussion and refinements in this <a class="reference external" href="https://mail.python.org/pipermail/python-dev/2012-January/115838.html">thread on python-dev</a> <a class="footnote-reference" href="#id5" id="id6">[3]</a>.</p>
<table class="docutils footnote" frame="void" id="id1" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id2">[1]</a></td><td><a class="reference external" href="http://bugs.python.org/msg152294">http://bugs.python.org/msg152294</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id3" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id4">[2]</a></td><td><a class="reference external" href="http://bugs.python.org/issue6210">http://bugs.python.org/issue6210</a></td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id5" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id6">[3]</a></td><td><a class="reference external" href="https://mail.python.org/pipermail/python-dev/2012-January/115838.html">https://mail.python.org/pipermail/python-dev/2012-January/115838.html</a></td></tr>
</tbody>
</table>
</div>
<div class="section" id="copyright">
<h1><a class="toc-backref" href="#id15">Copyright</a></h1>
<p>This document has been placed in the public domain.</p>
<!-- Local Variables:
mode: indented-text
indent-tabs-mode: nil
sentence-end-double-space: t
fill-column: 70
coding: utf-8
End: -->
</div>

